### ISSUE TITLE
Swagger - Invalid Chain Id

### ISSUE THREAD

**Issue by ismellike** [DA0-DA0/dao-dao-indexer#10]
I was trying to use the swagger UI to get the active proposal modules, and it is not passing the correct URL (missing chain id in url).
If you're dealing with this issue, you can just plug in the generated URL with the correct endpoint though: https://indexer.daodao.zone/neutron-1/contract/neutron1r6n0effjs6wv0pdcq2wk7nwn4qmahsqvvu9lnj08hhw8pzt9t0lsr8rccf/daoCore/activeProposalModules

![image](https://github.com/user-attachments/assets/7769659c-133f-4de8-8a9d-707928f24b17)
SS is from https://indexer.daodao.zone/neutron-1/docs#/contract/get_contract__address__daoCore_activeProposalModules

**Comment by NoahSaso** [comment]
thank you! fixed by c1c60ebf4029a8b7b4acda415b53246509e1d584
